from turtle import Turtle, Screen
import turtle
timmy=Turtle()
timmy.shape("turtle")
timmy.color("red")
timmy.forward(100)
timmy.left(90)
timmy.forward(100)
timmy.left(90)
timmy.forward(100)
timmy.left(90)
timmy.forward(100)
Screen=Screen()
Screen.exitonclick()
turtle.done()